# Generated by Django 3.2 on 2021-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oil',
            field=models.IntegerField(blank=True, max_length=3),
        ),
    ]
