# Generated by Django 3.2 on 2021-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_oil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oil',
            field=models.IntegerField(),
        ),
    ]
