# Generated by Django 3.2 on 2021-09-30 17:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registratsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('status', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Samarqand', 'Samarqand'), ('Jizzax', 'Jizzax'), ('Fargona', 'Fargona'), ('Suexandaryo', 'Suexandaryo'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='oil',
            field=models.IntegerField(max_length=3),
        ),
    ]
