# Generated by Django 3.2 on 2021-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oil',
            field=models.IntegerField(),
        ),
    ]
